--CREATE TABLE: Used to create template of table
--Example Syntax:
--CREATE TABLE table_name(
--column_name TYPE column_constraint,
--column_name TYPE column_constraint,
--table_constraint table_constraint
--)INHERITS existing_table_name;

--Example Syntax 2:
--CREATE TABLE players(
--player_id SERIAL column_constraint,
--column_name TYPE column_constraint,);

--SERIAL: 
--In PostgreSQL, a sequence is a special kind of databse object that generates a sequence of integers.
--A sequence is often used as the primary key column in a table.
--It will create a sequence object and set the next value
--generated by the sequence as the default value for the column.
--This is perfect for a primary key, because
--it logs unique integer entries for you automatically upon insertion.
--If a row is later removed, the column with the SERIAL data type will not adjust,
--marking the fact that a row was removed from the sequence, for example:
--1,2,3,5,6,7 shows that 4 was removed at some point from the database.
--SMALLSERIAL, SERIAL, BIGSERIAL
--Example Syntax:
--CREATE TABLE players(
--player_id SERIAL PRIMARY KEY,
--age SMALLINT NOT NULL);



